package com.alexcova.teenyjson;

public enum Automakers {
    FORD, TOYOTA, HONDA, BMW, MERCEDES, AUDI, VOLKSWAGEN, TESLA, NISSAN, PORSCHE, JAGUAR, LAND_ROVER, FERRARI, LAMBORGHINI,
    MASERATI, ALFA_ROMEO, FIAT, CHRYSLER, DODGE, JEEP, RAM, CHEVROLET, GMC, BUICK, CADILLAC, LINCOLN;
}
